service: pix-payment-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

  environment:
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}
    CERT_PATH: certs/cert.pem
    KEY_PATH: certs/key.key
    WEBHOOK_URL: ${env:WEBHOOK_URL}
    DYNAMODB_TABLE_NAME: pix_oauth_cache
    AWS_REGION: us-east-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_NAME}

functions:
  gerarPagamento:
    handler: dist/handler.gerarPagamento
    events:
      - http:
          path: gerar-pix
          method: post
          cors: true

  webhookPix:
    handler: dist/handler.webhookPix
    events:
      - http:
          path: webhook-pix
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-scriptable-plugin

custom:
  scriptHooks:
    before:deploy:deploy: npx ts-node scripts/validate-env.ts
    after:deploy:finalize: npx ts-node scripts/registrar-webhook.ts

resources:
  Resources:
    PixOAuthCacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
